# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: false

addons:
  apt:
    packages:
      - libgsl0-dev # for topicmodels

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
